#!/bin/bash
get_nexus_pid() {
  local NEXUS_PID="$(ps -ef|grep java|grep "${OPENSHIFT_DATA_DIR}nexus/lib/*"|awk '{ print $2 }')"
  echo "${NEXUS_PID}"
  return ${NEXUS_PID}
}

is_running() {
  local NEXUS_PID="$(get_nexus_pid)"
  if [ "${NEXUS_PID}" != "" ]; then
    echo "true"
    return 0
  else
    echo "false"
    return 1
  fi
}

echo -n "Starting nexus"
# Set some config without changing any files:
# https://support.sonatype.com/hc/en-us/articles/213465578-Can-I-override-Nexus-configuration-properties-with-environment-variables-
export NEXUS_APPLICATION_PORT=${OPENSHIFT_DIY_PORT}
export NEXUS_APPLICATION_HOST=${OPENSHIFT_DIY_IP}
export NEXUS_CONTEXT_PATH=/
export NEXUS_WORK=${OPENSHIFT_DATA_DIR}sonatype-work
export NEXUS_HOME=${OPENSHIFT_DATA_DIR}nexus

# Launch the Jetty server directly to avoid the wrapper opening extra ports and
# provoking error "unable to bind listener to any port in the range
# 32000-32999. (Permission denied)"
# Adapted from https://issues.sonatype.org/browse/NEXUS-7899
cd $NEXUS_HOME
java -cp $NEXUS_HOME/lib/*:$NEXUS_HOME/conf/ \
-Djava.util.prefs.userRoot="${OPENSHIFT_DATA_DIR}" \
-Djava.net.preferIPv4Stack=true \
-Dcom.sun.jndi.ldap.connect.pool.protocol="plain ssl" \
org.sonatype.nexus.bootstrap.Launcher \
$NEXUS_HOME/conf/jetty.xml \
$NEXUS_HOME/conf/jetty-requestlog.xml \
&> $NEXUS_HOME/logs/run.log &
NEXUS_PID="$(get_nexus_pid)"
STARTCOUNT=1
while [ ${STARTCOUNT} -le 5 ]; do
  if [ "$(is_running)" == "false" ]; then
    echo -n '.'
    sleep 5
  else
    break
  fi
  START=$(( $STARTCOUNT + 1 ))
done
echo ''
if [ "$(is_running)" == "false" ]; then
  DAEMONPID=$(get_nexus_pid)
  echo "Error! Nexus not started after 25 seconds!"
  exit 1
else
  echo "Nexus started"
  exit 0
fi
